import React from 'react'

const GlobalContext = React.createContext({
  customers: [],
  setCustomers: () => {},
  totalUnreadMsg: 0,
  setTotalUnreadMsg: () => {},
  selectedFile: null,
  setSelectedFile: () => {},
  selectedContact: null,
  setSelectedContact: () => {},
  labels: [],
  setLabels: () => {},
  isActive: false,
  setIsActive: () => {},
  showBefore: '',
  setShowBefore: () => {},
  openProfile: false,
  setOpenProfile: () => {},
  activeChat: false,
  setActiveChat: () => {},
  openInfo: true,
  setOpenInfo: () => {},
  searchContact: '',
  setSearchContact: () => {},
  mobileChatSidebar: false,
  setMobileChatSidebar: () => {},
  profileinfo: {},
  setProfileinfo: () => {},
  messFeed: [],
  setMessFeed: () => {},
  user: {},
  setUser: () => {},
  contacts: [],
  setContacts: () => {},
  chats: [],
  setChats: () => {},
  activeQtStatus: null,
  setActiveQtStatus: () => {},
  activeOrderStatus: 1,
  setActiveOrderStatus: () => {},
  activeLabelStatus: {},
  setActiveLabelStatus: () => {},
  enquiryDetails: null,
  setEnquiryDetails: () => {},
  forwardContacts: [],
  setForwardContacts: () => {},
  customMessages: [],
  setCustomMessages: () => {},
  inputMessage: '',
  setInputMessage: () => {},
  selectedCustomer: null,
  setSelectedCustomer: () => {},
  resetMsg: '',
  setResetMsg: () => {}
})

export default GlobalContext
